name: Run Unit Tests

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    test:
        name: Setup and Run Test Suite
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Launch Server
              run: docker compose up --detach server

            - name: Execute Tests
              run: docker compose up test

            - name: Cleanup
              run: docker compose down --volumes --remove-orphans
